config/routes.rb
Rails.application.routes.draw do




  resources :ideas
  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :ideas

end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  belongs_to :category

  
end

app/models/user.rb
class User < ApplicationRecord

  has_many :ideas

  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!

  def index
    @ideas = Idea.all.order('created_at DESC')
  end

  def show
  end

  def new
    @idea = current_user.ideas.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create

    @idea = current_user.ideas.build(idea_params)
    @idea.category_id = params[:category_id]
    if @idea.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def idea_params
      params.require(:idea).permit(:title, :content)
    end

    def find_idea
      @idea = Idea.find(params[:id])
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/_form.html.erb
        <%= simple_form_for @idea, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">

              <h2>Share your idea:</h2>

              <div class="category-select">
                <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category") %>
              </div>
              <%= f.input :title, label: false, placeholder: 'Title' %>
            </div>
            <div class="form-group text-center">
              <%= f.input :content, label: false, placeholder: 'Whats the big idea?'%>
            </div>
            <div class="form-group text-center">
              <%= f.button :submit, 'Share Idea', class: 'btn-lg btn-info btn-block' %>
            </div>
          </div>
        <% end %>

app/views/ideas/_idea.html.erb
<div class="ideas-wrapper">
  <div class="idea">
    <div class="idea-head">
      <div class="user-name">
        <%= idea.user.user_name %>
      </div>
      <div class="time-ago">
        <%= time_ago_in_words idea.created_at %>
      </div>
      <div class="title">
        <%= idea.title %>
      </div>
    </div>
    <div class="content">
      <div class="content-content">
        <%= idea.content %>
      </div>
    </div>
  </div>

</div>

app/views/ideas/_ideas.html.erb
<% @ideas.each do |idea| %>
  <%= render 'ideas/idea', idea: idea %>
<% end %>

app/views/ideas/index.html.erb
<div id="ideas">
  <%= render 'ideas/ideas' %>
</div>

app/views/ideas/new.html.erb
<div class="login-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-7 col-md-offset-2">
        <div class="log-in background">
          <div class="panel-heading">
            <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-transparent">
  <div class="container">

  <!--  <div class="navbar-header">
      <%= link_to "ShareYourIdea", root_path, class: "navbar-brand" %>
    </div> -->

    

    <ul class="nav navbar-nav navbar-right">

      <% if user_signed_in? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
        aria-expanded="false">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Category.all.each do |category| %>
            <li class="<%= 'active' if params[:category] == category.name %>">
              <%= link_to category.name, ideas_path(category: category.name), class: "Links" %>
            </li>
          <% end %>
        </ul>
      </li>

      <% if user_signed_in?%>
        <li><%= link_to "Share Idea", new_idea_path %></li>
      <%end%>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareYourIdea</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background">



        <%= render 'layouts/navbar' %>

        <!-- for devise -->
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

          <%= yield %>

          <%= debug(params) if Rails.env.development? %>




  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Homepage</h1>